theme: minima
title: "Keerthi's Blog"
author: MissKeerthi
email: keerthi1512g@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  this is my awesome description for this site and it doesn't make any sense lol.

# social links
twitter_username:  KTwts15 # DO NOT include the @ character, or else the build will fail!
github_username:  MissKeerthi # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
